services:
  postgres:
    image: postgres:16-alpine
    container_name: pqrs_postgres

    environment:
      POSTGRES_USER: pqrs_user
      POSTGRES_PASSWORD: pqrs_pass
      POSTGRES_DB: pqrs

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pqrs_user -d pqrs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

volumes:
  postgres_data: